# Generated by Django 6.0.4 on 2026-09-12 14:28

import apps.esports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0003_preserve_legacy_catalog_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proplayer',
            name='legacy_nickname',
            field=models.CharField(db_column='nickname', default=apps.esports.models.legacy_identifier, editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='proplayer',
            name='legacy_slug',
            field=models.SlugField(db_column='slug', default=apps.esports.models.legacy_identifier, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='proplayer',
            name='losses',
            field=models.PositiveIntegerField(default=0, verbose_name='поражения'),
        ),
        migrations.AlterField(
            model_name='proplayer',
            name='region',
            field=models.CharField(choices=[('americas', 'Америка'), ('europe', 'Европа'), ('se_asia', 'Юго-Восточная Азия'), ('china', 'Китай')], max_length=12, verbose_name='регион рейтинга'),
        ),
        migrations.AlterField(
            model_name='proplayer',
            name='wins',
            field=models.PositiveIntegerField(default=0, verbose_name='победы'),
        ),
    ]
