# Generated by Django 6.0.4 on 2026-09-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0006_team_liquipedia_roster'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteam',
            name='ranking_position',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='место в рейтинге Liquipedia'),
        ),
    ]
